### ISSUE TITLE
expose local.tls_key to output

### ISSUE THREAD

**Issue by kholisrag** [cloudposse/terraform-aws-ssm-tls-self-signed-cert#16]
## Describe the Feature

expose `local.tls_key` to output, helpful to sign intermediate ca, without reading the ssm or asm

## Expected Behavior

`local.tls_key` can be used to sign intermediate ca, like below : 

```hcl
  certificate_chain = {
    cert_pem        = var.cert_pem
    private_key_pem = var.private_key_pem
  }
```

## Use Case

lets say we generate root ca using this module, and want to generate the intermediate ca, using this module too

## Describe Ideal Solution

expose `local.tls_key` to output. any security concern?

**Comment by Nuru** [comment]
Exposing the key as output would be a major security issue, and we are not going to allow it.

**Comment by kholisrag** [comment]
> Exposing the key as output would be a major security issue, and we are not going to allow it.

ok then,
but fyi
lets say we want to create a root ca, intermediate ca, and the cert
we create root ca with this modules
then
to create the intermediate ca, we need to configure : 
- `var.use_locally_signed = true`
- `var.certificate_chain.private_key_pem`
- `var.certificate_chain.cert_pem`

and the `private_key_pem` is need to be filled with root ca cert key
